/* See emg_filter.h. */

#include "emg_filter.h"

#include <string.h>

/* Generated by tools/emg_filter_ref.py --emit-c from
 * scipy.signal.butter(2, [20, 450], btype='band', fs=2000) cascaded with
 * iirnotch at 50 Hz and 150 Hz, Q=30. */
const emg_biquad_coeffs_t emg_filter_20_450_notch50_at_2000[4] = {
        {124182526, 248365052, 124182526, -122776160, 107541674},
        {536870912, -1073741824, 536870912, -1026178378, 491484329},
        {535469054, -1057753083, 535469054, -1057753083, 534067196},
        {532687111, -949255383, 532687111, -949255383, 528503310},
};

/* Arithmetic shift with round-to-nearest. Plain >> truncates toward negative
 * infinity, which biases a zero-mean signal downward by half a quantum on
 * every section of every sample -- small individually, but it accumulates
 * into a DC offset in exactly the band a high-pass is supposed to remove. */
static inline int64_t shift_rounded(int64_t value, unsigned bits)
{
    return (value + ((int64_t)1 << (bits - 1))) >> bits;
}

bool emg_filter_init(emg_filter_t *filter, const emg_biquad_coeffs_t *sections,
                     uint8_t section_count)
{
    if (filter == NULL || sections == NULL) {
        return false;
    }
    if (section_count == 0u || section_count > EMG_FILTER_MAX_SECTIONS) {
        return false;
    }
    memcpy(filter->sections, sections,
           (size_t)section_count * sizeof(emg_biquad_coeffs_t));
    filter->section_count = section_count;
    emg_filter_reset(filter);
    return true;
}

void emg_filter_reset(emg_filter_t *filter)
{
    if (filter == NULL) {
        return;
    }
    memset(filter->state, 0, sizeof(filter->state));
}

int32_t emg_filter_step(emg_filter_t *filter, int16_t sample)
{
    if (filter == NULL || filter->section_count == 0u) {
        return 0;
    }

    int32_t value = (int32_t)sample << EMG_FILTER_STATE_BITS;
    for (uint8_t index = 0; index < filter->section_count; index++) {
        const emg_biquad_coeffs_t *coeffs = &filter->sections[index];
        emg_biquad_state_t *state = &filter->state[index];

        const int64_t accumulator = (int64_t)coeffs->b0 * value
                                  + (int64_t)coeffs->b1 * state->x1
                                  + (int64_t)coeffs->b2 * state->x2
                                  - (int64_t)coeffs->a1 * state->y1
                                  - (int64_t)coeffs->a2 * state->y2;
        const int32_t output =
            (int32_t)shift_rounded(accumulator, EMG_FILTER_COEFF_BITS);

        state->x2 = state->x1;
        state->x1 = value;
        state->y2 = state->y1;
        state->y1 = output;
        value = output;
    }
    return (int32_t)shift_rounded(value, EMG_FILTER_STATE_BITS);
}

void emg_filter_block(emg_filter_t *filter, const int16_t *input,
                      int32_t *output, size_t count)
{
    if (filter == NULL || input == NULL || output == NULL) {
        return;
    }
    for (size_t index = 0; index < count; index++) {
        output[index] = emg_filter_step(filter, input[index]);
    }
}
