/stereo/composite/decxin_gscam:
  ros__parameters:
    gscam_config: >-
      v4l2src
      device=/dev/v4l/by-id/usb-DECXIN_DECXIN_Camera_01.00.00-video-index0
      do-timestamp=true !
      image/jpeg,width=2560,height=960,framerate=30/1 !
      jpegdec ! videoconvert ! videorate drop-only=true max-rate=10 !
      video/x-raw,format=RGB,framerate=10/1
    camera_name: decxin_composite
    frame_id: decxin_composite_optical_frame
    image_encoding: rgb8
    use_gst_timestamps: true
    sync_sink: false

/composite_stereo_splitter:
  ros__parameters:
    input_topic: /stereo/composite/camera/image_raw
    left_topic: /stereo/left/image_rect
    right_topic: /stereo/right/image_rect
    left_camera_info_topic: /stereo/left/camera_info
    right_camera_info_topic: /stereo/right/camera_info
    left_camera_info_url: >-
      package://stereo_hand_observer/config/decxin_left.yaml
    right_camera_info_url: >-
      package://stereo_hand_observer/config/decxin_right.yaml
    left_camera_name: decxin_stereo_left_1280x960
    right_camera_name: decxin_stereo_right_1280x960
    expected_width: 2560
    expected_height: 960
    expected_encoding: rgb8
    left_frame_id: stereo_left_optical_frame
    right_frame_id: stereo_right_optical_frame
    swap_halves: false
    rectify_images: true
    output_width: 640
    output_height: 480
